
//showmovies
export const GET_MOVIES='GET-MOVIES'
export const SHOW_MOVIES='SHOW_MOVIES'

export const GET_HE_THONG='GET_HE_THONG'
export const GET_MOVIES_HT='GET_MOVIES_HT'
export const GET_CHI_TIET_HE_THONGS='GET_CHI_TIET_HE_THONGS'
export const CHANGE_HE_THONG='CHANGE_HE_THONG'
export const CHANGE_DANH_SACH_PHIM='CHANGE_DANH_SACH_PHIM'

export const CHANGEYOUTUBE='CHANGEYOUTUBE'
export const LICHCHIEUPHIMCHITIET='LICHCHIEUPHIMCHITIET'
export const CHANGELOADING='CHANGELOADING'
export const CHANGEHETHONGCTP='CHANGEHETHONGCTP'
export const CHANGERAPCHIEU='CHANGERAPCHIEU'
export const INITLICHCHIETCTP='INITLICHCHIETCTP'
export const GET_DANHSACHPHONGVE='GET_DANHSACHPHONGVE'
export const CHANGELOADINGRAPCHIEU='CHANGELOADINGRAPCHIEU'
export const CHANGELOADINGCTP='CHANGELOADINGCTP'

export const ADDGHE='ADDGHE'
export const REMOVEGHE='REMOVEGHE'

export const CHANGECOMBO='CHANGECOMBO'
